export const categories = [
    { id: "all", label: "Tất cả sản phẩm", count: 24 },
    { id: "t-shirt", label: "Áo thun", count: 8 },
    { id: "jeans", label: "Quần Jeans", count: 6 },
    { id: "underware", label: "Đồ lót", count: 5 },
    { id: "set", label: "Bộ outfit", count: 5 },
];

export const priceRanges = [
    { id: "p1", label: "Dưới 200.000đ" },
    { id: "p2", label: "200.000đ – 500.000đ" },
    { id: "p3", label: "500.000đ – 1.000.000đ" },
    { id: "p4", label: "1.000.000đ – 2.000.000đ" },
    { id: "p5", label: "Trên 2.000.000đ" },
];

export const colors = [
    { id: "black", hex: "#111111", label: "Đen" },
    { id: "white", hex: "#ffffff", label: "Trắng" },
    { id: "navy", hex: "#1a2a4a", label: "Navy" },
    { id: "grey", hex: "#9e9e9e", label: "Xám" },
    { id: "red", hex: "#c0392b", label: "Đỏ" },
    { id: "beige", hex: "#d4b896", label: "Be" },
    { id: "green", hex: "#2d6a4f", label: "Xanh lá" },
    { id: "blue", hex: "#2980b9", label: "Xanh dương" },
];

export const sizes = ["XS", "S", "M", "L", "XL", "XXL"];

export const products = [
    {
        id: '1',
        title: 'Áo thun basic',
        description: 'Áo thun ngắn tay, chất liệu cotton mềm mại và thoáng mát',
        image: '/images/products/ao-thun.jpg',
        price: 199000,
        originalPrice: 249000,
        category: 'Áo',
        rating: 4.8,
        reviewCount: 124,
        colors: ['Trắng', 'Đen', 'Xám'],
        sizes: ['S', 'M', 'L', 'XL'],
        stock: 45,
        isNew: true,
    },
    {
        id: '2',
        title: 'Quần Jeans ống suông',
        description: 'Quần Jeans form ống suông hiện đại, dễ phối đồ',
        image: '/images/products/quan-jeans.jpg',
        price: 499000,
        originalPrice: 599000,
        category: 'Quần',
        rating: 4.6,
        reviewCount: 89,
        colors: ['Xanh', 'Đen'],
        sizes: ['S', 'M', 'L', 'XL'],
        stock: 32,
        isNew: false,
    },
    {
        id: '3',
        title: 'Chân váy cách tân',
        description: 'Chân váy thiết kế cách tân, phù hợp đi làm và đi chơi',
        image: '/images/products/chan-vay.jpg',
        price: 299000,
        originalPrice: 359000,
        category: 'Váy',
        rating: 4.9,
        reviewCount: 156,
        colors: ['Đen', 'Be', 'Nâu'],
        sizes: ['S', 'M', 'L'],
        stock: 20,
        isNew: true,
    },
    {
        id: '4',
        title: 'Áo phao mùa đông',
        description: 'Áo phao giữ ấm tốt, thiết kế trẻ trung và hiện đại',
        image: '/images/products/ao-phao.jpg',
        price: 799000,
        originalPrice: 999000,
        category: 'Áo khoác',
        rating: 4.7,
        reviewCount: 67,
        colors: ['Đen', 'Xanh Navy'],
        sizes: ['M', 'L', 'XL', 'XXL'],
        stock: 15,
        isNew: false,
    },
]
